#!/usr/bin/env bash
# __version__ = "0.0.3"  # Semantic Versioning:  Version = Major.Minor.Patch  (bash port of my_trigger.bat)
#
# my_trigger_pool.sh — one-shot pool trigger. Calls my_trigger.sh in --mode pool with everything
# pre-filled, so a single run kicks off the real deployment. Submitter is auto-generated by
# my_trigger.sh (yRocket-<yyyymmdd-HHMM>-<tz>), so it is not passed here.
#
#   ./my_trigger_pool.sh
#
# Bump --git-commit after every payload change (the pool runs the pinned SHA, not repo HEAD).
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$here/my_trigger.sh" --mode pool \
  --prefect-block yrocket \
  --prefect-api-url http://192.168.0.13:4200/api \
  --prefect-deployment pipeline/low_deployment \
  --git-repo https://github.com/ykim2718/SandBox4Git.git \
  --git-commit 95153312753021be0e4c09d04a387d1864de9569 \
  --minio-key electric_power_consumption/v0/powerconsumption.csv \
  --payload my_flow.py
